import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './../components/store/Headers'; 
import Search from './../components/store/modal/Search'; 
import LoginModal from './../components/store/modal/Login';
import CartModal from './../components/store/modal/CartModal';
import FavoritesModal from "@/components/store/modal/FavoritesModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />      
        {children}
        <Search/>
        <LoginModal />
        <CartModal />
      </body>
    </html>
  );
}
