import "./globals.css";

export const metadata = {
  title: "granddesign",
  description: "Generated by Wiser",

  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        {children}
      </body>
    </html>
  );
}
