// // import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata = {
//   title: "granddesign",
//   description: "Generated by Wiser",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//        {children}
//       </body>
//     </html>
//   );
// }


import "./globals.css";

export const metadata = {
  viewport: "width=device-width, initial-scale=1",
  title: {
    default: "گراند دیزاین | شرکت طراحی، معماری و برندینگ",
    template: "%s | گراند دیزاین",
  },

  description:
    "گراند دیزاین شرکت تخصصی طراحی و دیزاین با تمرکز بر طراحی معماری، طراحی داخلی، طراحی سایت، UI/UX، برندینگ و سئو برای رشد کسب‌وکارها در لاهیجان و استان گیلان.",

  metadataBase: new URL("https://granddesign.ir"),

  // viewport: "width=device-width, initial-scale=1",

  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },

  openGraph: {
    title: "گراند دیزاین | شرکت طراحی و دیزاین حرفه‌ای",
    description:
      "گراند دیزاین ارائه‌دهنده خدمات تخصصی طراحی معماری، طراحی داخلی، طراحی سایت، UI/UX، برندینگ و سئو برای توسعه و رشد کسب‌وکارها در لاهیجان و گیلان.",
    url: "https://granddesign.ir",
    siteName: "Grand Design",
    locale: "fa_IR",
    type: "website",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
