//   // import { Geist, Geist_Mono } from "next/font/google";
//   import "./globals.css";

//   // const geistSans = Geist({
//   //   variable: "--font-geist-sans",
//   //   subsets: ["latin"],
//   // });

//   // const geistMono = Geist_Mono({
//   //   variable: "--font-geist-mono",
//   //   subsets: ["latin"],
//   // });

// export const metadata = {
//   title: "granddesign",
//   description: "Generated by Wiser",
//   icons: {
//     icon: "https://ftp.granddesign.ir/images/20241027_175834.png",
//     shortcut: "/favicon.ico",
//     apple: "/apple-touch-icon.png",
//   },
// };


//   export default function RootLayout({ children }) {
//     return (
//       <html lang="en">
//         <body
//           // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//         {children}
//         </body>
//       </html>
//     );
//   }




import "./globals.css";

export const metadata = {
  title: {
    default: "گراند دیزاین | طراحی سایت و برندینگ در لاهیجان",
    template: "%s | گراند دیزاین",
  },

  description:
    "گراند دیزاین ارائه‌دهنده طراحی سایت حرفه‌ای، UI/UX، برندینگ و سئو برای کسب‌وکارها در لاهیجان و گیلان.",

  metadataBase: new URL("https://granddesign.ir"),

  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },

  openGraph: {
    title: "گراند دیزاین | طراحی سایت در لاهیجان",
    description:
      "طراحی سایت، برندینگ و سئو برای رشد کسب‌وکارهای محلی در لاهیجان و گیلان",
    url: "https://granddesign.ir",
    siteName: "Grand Design",
    locale: "fa_IR",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
